name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: check npm version
        run: npm --version

      - name: Install dependencies
        run: |
          npm install

      - name: Lint
        run: cd handlers && npm run lint

      - name: Type check
        run: cd handlers && npm run build

      - name: Run unit tests
        run: cd handlers && npm test

      - name: Run E2E tests
        run: cd handlers && npm run test:e2e

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./handlers/coverage
